package com.impact;

import com.impact.proxy.CommonProxy;
import com.impact.proxy.WorldTick;
import com.impact.register.IGM_Blocks;
import com.impact.register.IGM_Items;
import com.impact.register.SSBodies;
import cpw.mods.fml.common.FMLCommonHandler;
import cpw.mods.fml.common.Mod;
import cpw.mods.fml.common.Mod.EventHandler;
import cpw.mods.fml.common.ModMetadata;
import cpw.mods.fml.common.SidedProxy;
import cpw.mods.fml.common.event.FMLInitializationEvent;
import cpw.mods.fml.common.event.FMLPostInitializationEvent;
import cpw.mods.fml.common.event.FMLPreInitializationEvent;
import galaxyspace.api.IBodiesHandler;
import micdoodle8.mods.galacticraft.core.tick.TickHandlerServer;

import java.util.ArrayList;
import java.util.Arrays;
import java.util.List;

@Mod(
        name = "Impact | Galactic Module",
        version = ImpactGalacticModule.VERSION,
        modid = ImpactGalacticModule.MODID,
        dependencies =
                "required-after:GalacticraftCore@[3.0.12,); " +
                "required-after:GalacticraftMars; " +
                "required-after:GalaxySpace;"
)
public class ImpactGalacticModule {

    public static final String MODID = "Impact|GalacticModule";
    public static final String VERSION = "0.0.1";
    public static final String ASSET_PREFIX = "Impact|GalacticModule".toLowerCase();
    public static final String TEXTURE_PATH = "Impact".toLowerCase();

    @Mod.Instance("Impact|GalacticModule")
    public static ImpactGalacticModule instance;

    @SidedProxy(
            clientSide = "com.impact.proxy.ClientProxy",
            serverSide = "com.impact.proxy.CommonProxy"
    )
    public static CommonProxy proxy;

    public static List<IBodiesHandler> bodies = new ArrayList();

    static {
        bodies.add(new SSBodies());
    }

    public ImpactGalacticModule() {}

    @EventHandler
    public void init(FMLInitializationEvent event) {
        for (IBodiesHandler list : bodies) {
            list.init(event);
        }
    }

    @EventHandler
    public void preInit(FMLPreInitializationEvent event) {
        IGM_Blocks.regiserBlocks();
        IGM_Items.registerItems();
        this.initModInfo(event.getModMetadata());
        for (IBodiesHandler list : bodies) {
            list.preInit(event);
        }
    }

    @EventHandler
    public void postInit(FMLPostInitializationEvent event) {
        for (IBodiesHandler list : bodies) {
            list.postInit(event);
        }
        FMLCommonHandler.instance().bus().register(new WorldTick());
    }

    private void initModInfo(ModMetadata info) {
        info.autogenerated = false;
        info.modId = ASSET_PREFIX;
        info.name = "Impact | Galactic Module";
        info.version = VERSION;
        info.description = "Module for Impact";
        info.authorList = Arrays.asList("Impact Team");
    }
}
